using System;
using System.Collections.Generic;
using YARG.Core;

namespace YARG.Networking.Abstraction
{
    /// <summary>
    /// Common lobby information structure used across all networking implementations.
    /// </summary>
    [Serializable]
    public class LobbyInfo
    {
        public string LobbyId { get; set; }
        public string LobbyName { get; set; }
        public string HostName { get; set; }
        public int CurrentPlayers { get; set; }
        public int MaxPlayers { get; set; }
        public LobbyPrivacyMode PrivacyMode { get; set; }
        public bool HasPassword { get; set; }
        public string Password { get; set; }
        public bool IsActive { get; set; }
        public string IpAddress { get; set; }
        public int Port { get; set; }
        public int PublicPort { get; set; }
        public string PublicAddress { get; set; }
        public string TransportId { get; set; }
        public string[] PlayerNames { get; set; }
        public int[] PlayerInstruments { get; set; }
        
        // Gameplay settings visible before joining
        /// <summary>
        /// Whether No Fail mode is enabled for this lobby.
        /// </summary>
        public bool NoFailMode { get; set; }
        
        /// <summary>
        /// Whether only shared songs can be played.
        /// </summary>
        public bool SharedSongsOnly { get; set; }
        
        /// <summary>
        /// Maximum band size (0 = unlimited).
        /// </summary>
        public int BandSize { get; set; }
        
        /// <summary>
        /// Allowed game modes for this lobby. Empty means all modes allowed.
        /// </summary>
        public List<GameMode> AllowedGameModes { get; set; } = new();
        
        /// <summary>
        /// Last time this lobby was seen/updated (for discovery staleness tracking).
        /// </summary>
        public DateTime LastSeen { get; set; } = DateTime.UtcNow;
        
        /// <summary>
        /// Estimated ping/latency to this lobby in milliseconds.
        /// -1 indicates ping has not been measured.
        /// </summary>
        public int Ping { get; set; } = -1;
        
        /// <summary>
        /// Session type: Server (0) = persistent/bookmarkable, Lobby (1) = ephemeral UPnP/not bookmarkable.
        /// </summary>
        public int SessionType { get; set; }
        
        /// <summary>
        /// The lobby code for this session (Lobby mode only).
        /// This is a 6-character code generated by the introducer that players can use to join.
        /// Null or empty for Server mode sessions.
        /// </summary>
        public string LobbyCode { get; set; }
        
        /// <summary>
        /// Whether this lobby is hosted by a dedicated server (no host player).
        /// When true, the first connecting player becomes the host.
        /// </summary>
        public bool IsDedicatedServer { get; set; }
        
        /// <summary>
        /// Returns true if this is a Server session (persistent, can be bookmarked).
        /// </summary>
        public bool IsServer => SessionType == 0;
        
        /// <summary>
        /// Returns true if this is a Lobby session (ephemeral UPnP, should not be bookmarked).
        /// </summary>
        public bool IsLobby => SessionType == 1;
        
        /// <summary>
        /// Returns how long ago this lobby was seen.
        /// </summary>
        public TimeSpan TimeSinceLastSeen => DateTime.UtcNow - LastSeen;
        
        /// <summary>
        /// Returns true if the lobby is considered fresh (seen within the last 15 seconds).
        /// This threshold is set to be longer than the discovery broadcast interval (3s)
        /// to account for network delays and processing time.
        /// </summary>
        public bool IsFresh => TimeSinceLastSeen.TotalSeconds < 15;
    }

    /// <summary>
    /// Privacy mode for lobbies.
    /// </summary>
    public enum LobbyPrivacyMode
    {
        /// <summary>
        /// Lobby is publicly visible via LAN discovery and introducers.
        /// </summary>
        Public,
        
        /// <summary>
        /// Lobby is visible but requires a password to join.
        /// </summary>
        Private,
        
        /// <summary>
        /// Lobby is not advertised - only joinable via direct connect.
        /// </summary>
        Unlisted
    }
}
